spring:
  config:
    import: configserver:http://localhost:8888
    name: deployment-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

hosts:
  logstash: localhost



producers:
  bootstrap-servers: localhost:9092
  topic:
    create-instance:
      name: create_instance
    project-deletion-exception:
      name: project_deletion_exception

consumers:
  bootstrap-servers: localhost:9092
  topic:
    save-hosting:
      name: save_hosting
    update-deployment-status:
      name: update_deployment_status
    delete-deployment:
      name: project_deletion_initiated
  groupid:
    save-hosting:
      name: save_hosting
    update-deployment-status:
      name: update_deployment_status
    delete-deployment:
      name: project_deletion_initiated

subdomain:
  endpoint: http://localhost:8000