spring:
  config:
    import: configserver:http://localhost:8888
    name: deployment-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

hosts:
  logstash: localhost



producers:
  bootstrap-servers: localhost:9092
  topic1:
    name: create_instance

consumers:
  bootstrap-servers: localhost:9092
  topic1:
    name: save_hosting
  topic2:
    name: project_deletion_initiated
  groupid:
    name: hosting

subdomain:
  endpoint: http://localhost:8000