server:
  port: 0

spring:
  profiles:
    include: kafka
  application:
    name: deployment-service
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: "*"


producers:
  topic:
    create-instance:
      name: create-instance
    project-deletion-exception:
      name: project-deletion-exception
    update-domain-name-exception:
      name: update-domain-name-exception

consumers:
  topic:
    save-hosting:
      name: save-hosting
    update-deployment-status:
      name: update-deployment-status
    delete-deployment:
      name: project-deletion-initiated
    update-domain-name:
      name: update-domain-name

  groupid:
    save-hosting:
      name: save_hosting
    update-deployment-status:
      name: update_deployment_status
    delete-deployment:
      name: project_deletion_initiated
    update-hosting-status:
      name: update_hosting_status
