server:
  port: 0

spring:
  application:
    name: deployment-service




#  cloud:
#    routes:
#      - id: project-service
#        uri: lb://PROJECT-SERVICE
#        predicates:
#          - Path=/project-service/**

<<<<<<< Updated upstream
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
=======
#eureka:
#  instance:
#    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance.id:${random.value}}
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

producers:
  bootstrap-servers: localhost:9092
  topic1:
    name: create_instance

consumers:
  bootstrap-servers: localhost:9092
  topic1:
    name: save_hosting
  groupid:
    name: hosting

management:
  tracing:
    sampling:
      probability: 1.0

hosts:
  logstash: localhost
>>>>>>> Stashed changes
