spring:
  config:
    import: optional:configserver:http://host.docker.internal:8888
    name: deployment-service

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/

hosts:
  logstash: host.docker.internal



producers:
  bootstrap-servers: localhost:9092
  topic1:
    name: create_instance

consumers:
  bootstrap-servers: localhost:9092
  topic1:
    name: save_hosting
  groupid:
    name: hosting