spring:
  config:
    import: optional:configserver:http://config-server:8888
    name: deployment-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

hosts:
  logstash: 10.178.0.6

producers:
  bootstrap-servers: 10.178.0.6:9092
  topic1:
    name: create_instance
  topic2:
    name: project_deletion_exception


consumers:
  bootstrap-servers: 10.178.0.6:9092
  topic:
    save-hosting:
      name: save_hosting
    update-deployment-status:
      name: project_deletion_initiated
    delete-deployment:
      name: project_deletion_initiated
  groupid:
    save-hosting:
      name: save_hosting
    update-deployment-status:
      name: project_deletion_initiated
    delete-deployment:
      name: project_deletion_initiated


subdomain:
  endpoint: http://10.178.0.6:8000