server:
  port: 0

spring:
  application:
    name: deployment-service

---

spring:
  profiles:
    include: kafka-dev
    active: dev

---

spring:
  profiles:
    include: kafka-prod
    active: prod