server:
  port: 0

spring:
  profiles:
    include: kafka
  application:
    name: deployment-service
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: "*"


producers:
  topic:
    create-instance:
      name: create_instance

consumers:
  topic:
    save-hosting:
      name: save_hosting
    update-deployment-status:
      name: project_deletion_initiated
    delete-deployment:
      name: project_deletion_initiated
  groupid:
    save-hosting:
      name: save_hosting
    update-deployment-status:
      name: project_deletion_initiated
    delete-deployment:
      name: project_deletion_initiated
