spring:
  config:
    import: optional:configserver:http://config-server:8888
    name: deployment-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

hosts:
  logstash: 10.178.0.6

subdomain:
  endpoint: http://10.178.0.121:8000