server:
  port: 0

spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:8888
    name: auth-service

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
