spring:
  config:
    import: optional:configserver:http://host.docker.internal:8888
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
