server:
  port: 0

spring:
  application:
    name: auth-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://config-server:8888
    name: auth-service

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    kr:
      kro:
        ddalkak:
          auth: DEBUG
