name: ddalkak-docker-compose
version: "3.9"

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ddalkak
      - POSTGRES_USER=ddalkak
      - POSTGRES_PASSWORD=ddalkak
  
  redis:
    image: redis:6.0
    restart: always
    ports:
      - "6379:6379"

  
volumes:
  postgres_data:
