name: ddalkak-docker-compose
version: "3.9"

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ddalkak
      - POSTGRES_USER=ddalkak
      - POSTGRES_PASSWORD=ddalkak
    networks:
      - spring-network

  redis:
    image: redis:6.0
    restart: always
    ports:
      - "6379:6379"
    networks:
      - spring-network
    entrypoint: redis-server --requirepass ddalkak --maxmemory 128mb

  eureka-server:
    container_name: eureka-server
    build: eureka-server
    ports:
      - 8761:8761
    networks:
      - spring-network
    depends_on:
      - db
      - redis
      - elasticsearch
      - kibana
      - logstash
  
  config-server:
    container_name: config-server
    build: config-server
    ports:
      - 8888:8888
    networks:
      - spring-network
    depends_on:
      - db
      - redis
      - elasticsearch
      - kibana
      - logstash

  gateway-service:
    container_name: gateway-service
    build: 
      context: gateway-service
      dockerfile: Dockerfile.prod
    ports:
      - 8000:8000
    networks:
      - spring-network
    depends_on:
      - db
      - redis
      - elasticsearch
      - kibana
      - logstash

  # compute-service:
  #   container_name: compute-service
  #   build: compute-service
  #   depends_on:
  #     - eureka-server
  #     - gateway-service
  
  auth-service:
    container_name: auth-service
    build: 
      context: auth-service
      dockerfile: Dockerfile.prod
    depends_on:
      - eureka-server
      - gateway-service
      - config-server
      - elasticsearch
      - kibana
      - logstash

    networks:
      - spring-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.23
    container_name: elasticsearch
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9300:9300
      - 9200:9200
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - spring-network
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.23
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - spring-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.23
    container_name: logstash
    command:
      logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./docker_config:/etc/logstash/conf.d
    ports:
      - 5000:5000  
    depends_on:
      - elasticsearch
    networks:
      - spring-network

volumes:
  postgres_data:
  elasticsearch_data: 

networks:
  spring-network:
