server:
  port: 0

spring:
  profiles:
    include: kafka
  application:
    name: compute-service
  kafka:
    consumer:
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

consumer:
  topics:
    compute-create:
      name: compute-create

    user-create:
      name: user-create