spring:
  config:
    import: optional:configserver:http://host.docker.internal/:8888
    name: compute-service

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/

hosts:
  logstash: host.docker.internal