server:
  port: 0

spring:
  application:
    name: compute-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://host.docker.internal:8888
    name: compute-service

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/