server:
  port: 8000

spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: lb://AUTH-SERVICE
            predicates:
              - Path=/auth/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true