server:
  port: 8000

spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationHeaderFilter
        - id: project-service
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/v1/project/**
          filters:
            - AuthenticationHeaderFilter

        - id: compute-service
          uri: lb:ws://COMPUTE-SERVICE
          predicates:
              - Path=/ws/**

        - id: deployment-service
          uri: lb://DEPLOYMENT-SERVICE
          predicates:
            - Path=/v1/deployment/**
          filters:
            - AuthenticationHeaderFilter
