server:
  port: 0

spring:
  application:
    name: project-service
  config:
    import: optional:configserver:http://localhost:8888
    name: project-service

---

spring:
  profiles:
    include: kafka-dev
    active: dev

---

spring:
  profiles:
    include: kafka-prod
    active: prod

