server:
  port: 0

spring:
  profiles:
    include: kafka
  application:
    name: project-service
  config:
    import: optional:configserver:http://localhost:8888
    name: project-service

producers:
  bootstrap-servers: 10.178.0.6:9092
  topic:
    project-deletion-initiated:
      name: project-deletion-initiated
    update-domain-name:
      name: update-domain-name

consumers:
  bootstrap-servers: 10.178.0.6:9092
  topic:
    project-deletion-exception:
      name: project-deletion-exception
    update-domain-name-exception:
      name: update-domain-name-exception
  groupid:
    project-deletion-group:
      name: project_deletion_group
    update-hosting-status:
      name: update_hosting_status

