server:
  port: 0

spring:
  application:
    name: project-service
  config:
    import: optional:configserver:http://localhost:8888
    name: project-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: project-deletion-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

producers:
  bootstrap-servers: localhost:9092
  topic1:
    name: project_deletion_initiated

consumers:
  bootstrap-servers: localhost:9092
  topic1:
    name: project_deletion_exception
  groupid:
    name: project-deletion-group

management:
  tracing:
    sampling:
      probability: 1.0

hosts:
  logstash: localhost

  #eureka:
  #  instance:
  #    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  #  client:
  #    fetch-registry: true
  #    register-with-eureka: true
  #    service-url:
  #      defaultZone: http://localhost:8761/eureka/
