server:
  port: 0

spring:
  profiles:
    include: kafka-prod
  config:
    import: optional:configserver:http://config-server:8888
    name: project-service

producers:
  bootstrap-servers: 10.178.0.6:9092
  topic1:
    name: project_deletion_initiated

consumers:
  bootstrap-servers: 10.178.0.6:9092
  topic1:
    name: project_deletion_exception
  groupid:
    name: project-deletion-group

hosts:
  logstash: 10.178.0.6

