name: subtree-matrix

on: [push]

jobs:
  sync-downstream:

    runs-on: ubuntu-latest

    name: Push entire GitHub contents to GitLab's server directory

    steps:
      # GitHub 리포지토리 체크아웃
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add upper https://oauth2:9-hymdP5xVN_HrdaNw8Y@lab.ssafy.com/s11-blochain-transaction-sub1/S11P21C108.git

      # GitHub 루트 디렉토리 전체를 GitLab의 server 디렉토리에 서브트리로 푸시
      - name: Push Subtree to GitLab's server directory
        uses: nxtlvlsoftware/git-subtree-action@1.1
        with:
          repo: 'https://oauth2:9-hymdP5xVN_HrdaNw8Y@lab.ssafy.com/s11-blochain-transaction-sub1/S11P21C108.git'
          path: '.'   # GitHub의 전체 루트 디렉토리를 서브트리로 푸시
          prefix: 'server' # GitLab에서 이 내용을 server 디렉토리로 푸시
          branch: master   # GitLab의 master 브랜치로 푸시
          force: true      # 강제 푸시
