name: Sync subtree to upper repository

on:
  push:
    branches:
      - master  # 하위 트리의 master 브랜치에 변경 사항이 있을 때 트리거
jobs:
  sync-subtree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # 현재 리포지토리의 코드를 체크아웃

      - name: Configure Git
        run: |
          git config --global user.name "sgo722"
          git config --global user.email "sgo722@naver.com"

      - name: Clone upper repository
        run: |
          git clone https://oauth2:9-hymdP5xVN_HrdaNw8Y@lab.ssafy.com/s11-blochain-transaction-sub1/S11P21C108.git
          cd S11P21C108

      - name: Pull and update subtrees
        run: |
          git subtree add --prefix=config https://oauth2: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@github.com/sunsuking/ddalkak_config.git main --squash
          git subtree add --prefix=tunneling https://oauth2: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@github.com/sunsuking/tunelling.git master --squash
          git subtree add --prefix=server https://oauth2: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@github.com/sunsuking/ddalkak.git master --squash
          git subtree add --prefix=client https://oauth2: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@github.com/ljjunh/ttalkak.git master --squash

      - name: Commit and push changes to upper repository
        run: |
          git add .
          git commit -m "Update subtrees"
          git push origin master