name: Sync subtree to upper repository

on:
  push:
    branches:
      - master  # 하위 트리의 main 브랜치에 변경 사항이 있을 때 트리거

jobs:
  sync-subtree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout submodule
        uses: actions/checkout@v2  # 하위 트리의 코드를 체크아웃하여 가져옵니다.

      - name: Add remote only if not exists
        run: |
          git remote | grep upper || git remote add upper https://lab.ssafy.com/s11-blochain-transaction-sub1/S11P21C108.git  # 원격 저장소가 없을 때만 추가

      - name: Push changes to upper repository (GitLab)
        run: |
          git subtree push --prefix=. https://lab.ssafy.com/s11-blochain-transaction-sub1/S11P21C108.git main:server