name: Sync subtree to upper repository

on:
  push:
    branches:
      - master  # 하위 트리의 master 브랜치에 변경 사항이 있을 때 트리거

jobs:
  sync-subtree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout submodule
        uses: actions/checkout@v2  # 현재 리포지토리의 코드를 체크아웃

      - name: Remove .github directory
        run: |
          rm -rf .github  # .github 디렉토리 삭제

      - name: Authenticate to GitLab and add remote
        run: |
          git config --global user.name "양준영"
          git config --global user.email "sgo722@naver.com"
          git remote add upper https://oauth2:9-hymdP5xVN_HrdaNw8Y@lab.ssafy.com/s11-blochain-transaction-sub1/S11P21C108.git  # GitLab 저장소에 인증을 추가
          git fetch upper  # GitLab 저장소의 최신 상태 가져오기

      - name: Push changes to upper repository
        run: |
          git fetch upper  # GitLab 저장소 최신 상태 가져오기
          git checkout upper/master  # GitLab의 master 브랜치 체크아웃
          mkdir -p server  # server 디렉토리가 없으면 생성
          rsync -av --exclude='server' ./ server/  # server 디렉토리를 제외하고 모든 파일을 복사
          git add server/
          git commit -m "Sync from Github master branch to server directory"
          git push upper HEAD:master  # GitLab master 브랜치에 푸시
