name: Sync to upper repository

on:
  push:
    branches:
      - master  # 하위 리포지토리의 master 브랜치에 변경 사항이 발생하면 실행

jobs:
  sync-to-upper:
    runs-on: ubuntu-latest

    steps:
      # 1. 하위 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # 2. 상위 리포지토리에 대한 인증 설정
      - name: Set up Git
        run: |
          git config --global user.name "양준영"
          git config --global user.email "sgo722@naver.com"
          git remote add upper https://oauth2:9-hymdP5xVN_HrdaNw8Y@lab.ssafy.com/s11-blochain-transaction-sub1/S11P21C108.git

      # 3. 하위 리포지토리에서 최근 커밋 메시지 가져오기
      - name: Get last commit message
        id: last_commit
        run: |
          last_commit_msg=$(git log -1 --pretty=%B)
          echo "::set-output name=message::$last_commit_msg"

      # 4. 상위 리포지토리의 특정 디렉토리로 모든 내용 복사
      - name: Copy all files to /server directory in upper repo
        run: |
          git fetch upper
          git checkout master
          mkdir -p server  # 상위 리포지토리의 /server 디렉토리를 생성
          rsync -av --exclude='.git' . ./server  # 모든 파일을 /server 디렉토리로 복사

      # 5. 상위 리포지토리에 푸시
      - name: Push to upper repository
        run: |
          git add .
          git commit -m "${{ steps.last_commit.outputs.message }}"  # 최근 커밋 메시지를 사용
          git push upper master
