name: Sync subtree to upper repository

on:
  push:
    branches:
      - master  # 하위 트리의 master 브랜치에 변경 사항이 있을 때 트리거

jobs:
  sync-subtree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout submodule
        uses: actions/checkout@v2  # 현재 리포지토리의 코드를 체크아웃

      - name: Authenticate to GitLab and add remote
        run: |
          git config --global user.name "양준영".
          git config --global user.email "sgo722@naver.com"
          git remote add upper https://oauth2:9-hymdP5xVN_HrdaNw8Y@lab.ssafy.com/s11-blochain-transaction-sub1/S11P21C108.git  # GitLab 저장소에 인증을 추가
      - name: Push changes to upper repository
        run: |
          git clone https://oauth2:9-hymdP5xVN_HrdaNw8Y@lab.ssafy.com/s11-blochain-transaction-sub1/S11P21C108.git
          cd S11P21C108
          
          git subtree pull --prefix=config https://github.com/sunsuking/ddalkak_config.git main --squash
          git subtree pull --prefix=tunneling https://github.com/sunsuking/tunelling.git master --squash
          git subtree pull --prefix=config https://github.com/sunsuking/ddalkak_config.git main --squash
          git subtree pull --prefix=server https://github.com/sunsuking/ddalkak.git master --squash
          git subtree pull --prefix=client https://github.com/ljjunh/ttalkak.git master --squash
          
          git add .
          git commit -m "Update subtrees"
          git push upper master