name: Sync subtree to upper repository

on:
  push:
    branches:
      - master  # master 브랜치에 변경 사항이 있을 때 트리거

jobs:
  sync-subtree:
    runs-on: ubuntu-latest

    steps:
      # GitHub 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # GitLab 인증 설정
      - name: Authenticate to GitLab
        run: |
          git config --global user.name "양준영"
          git config --global user.email "sgo722@naver.com"
          git remote add upper https://oauth2:9-hymdP5xVN_HrdaNw8Y@lab.ssafy.com/s11-blochain-transaction-sub1/S11P21C108.git

      # .github 디렉토리를 제외하고 푸시
      - name: Remove .github from subtree
        run: |
          git rm -r --cached .github  # .github 디렉토리를 임시로 제거
          git commit -m "Remove .github directory for subtree push"

      # 서브트리 푸시
      - name: Push changes to GitLab's server directory
        run: |
          git subtree push --prefix=. upper master  # GitHub 전체 내용을 GitLab master 브랜치의 server 디렉토리로 푸시

      # .github 디렉토리 복원
      - name: Restore .github directory
        run: |
          git reset --hard HEAD~1  # .github 디렉토리 복원
