name: Sync subtree to upper repository

on:
  push:
    branches:
      - master  # 하위 트리의 master 브랜치에 변경 사항이 있을 때 트리거

jobs:
  sync-subtree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout submodule
        uses: actions/checkout@v2  # 현재 리포지토리의 코드를 체크아웃

      - name : Install git filter-repo
        run : |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install git-filter-repo

      - name : Remove Github Actions workflow directory
        run : |
          git filter-repo --path .github --invert-paths # github 디렉토리 삭제

      - name: Authenticate to GitLab
        run: |
          git config --global user.name "양준영"
          git config --global user.email "sgo722@naver.com"
          git remote add upper https://oauth2:9-hymdP5xVN_HrdaNw8Y@lab.ssafy.com/s11-blochain-transaction-sub1/S11P21C108.git  # GitLab 저장소에 인증을 추가

      - name: Push changes to upper repository
        run: |
          git push upper master:server